name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Tjek ud koden fra GitHub
      - name: Checkout code
        uses: actions/checkout@v2

      # Sæt op Java miljøet
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adoptopenjdk'

      # Installer afhængigheder og kør test
      - name: Build and Test with Maven
        run: |
          mvn clean install
          mvn test

      # Kør statisk kodeanalyse med Qodana
      - name: Run Qodana Static Code Analysis
        uses: JetBrains/qodana-action@v1
        with:
          token: ${{ secrets.QODANA_TOKEN }}

      # Upload testresultater til GitHub Actions
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: target/test-classes

      # Opbevar Qodana rapporter
      - name: Upload Qodana report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: qodana-report
          path: .qodana
